=== mhamdadel/portfolio12/projects/xml/d1/lab1/lib.dtd
<!ELEMENT library (location,description,books)>
<!ATTLIST library id CDATA #REQUIRED>
<!ELEMENT location (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT books (book*)>
<!ELEMENT book (isbn, author, preface, parts)>
<!ATTLIST book id CDATA #REQUIRED>
<!ATTLIST book title CDATA #REQUIRED>
<!ELEMENT isbn #IMPLIED>
<!ELEMENT author (#PCDATA)>
<!ELEMENT preface #IMPLIED>
<!ELEMENT parts (part*)>
<!ELEMENT part (chapters)>
<!ATTLIST part title CDATA #REQUIRED>
<!ATTLIST part id CDATA #REQUIRED>
<!ELEMENT chapters (chapter*)>
<!ELEMENT chapter (summary, sections)>
<!ATTLIST chapter id CDATA #REQUIRED>
<!ATTLIST chapter title CDATA #REQUIRED>
<!ELEMENT summary (#PCDATA)>
<!ELEMENT sections (section*)>
<!ELEMENT section (pharagraph*)>
<!ATTLIST section id CDATA #REQUIRED>
<!ELEMENT pharagraph (#PCDATA)>
<!ATTLIST pharagraph id CDATA #REQUIRED>

=== mhamdadel/portfolio12/projects/xml/d1/lab1/lib.xml
<?xml version="1.0"?>
<!DOCTYPE library SYSTEM "lib.dtd">

<library id="1">
    <location>
        Haram-Giza ,Egypt
    </location>

    <description>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit.
        Quas neque saepe cum quo aliquid provident ullam! Animi 
        distinctio omnis doloremque eligendi id perferendis in iusto!
    </description>

    <books>
        <book id="1" title="How to use your brain">
            <isbn></isbn>
            <author>Muhammed Adel</author>
            <preface></preface>
            <parts>
                <part id="1" title="be smart be creative">
                    <chapters>
                        <chapter id="1" title="how to be smart">
                            <summary>Lorem ipsum dolor sit amet.</summary>
                            <sections>
                                <section id="1">
                                    <pharagraph id="1">Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, perferendis!</pharagraph>
                                </section>
                                <section id="2">
                                    <pharagraph id="1">Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, perferendis!</pharagraph>
                                </section>
                            </sections>
                        </chapter>
                        <chapter id="1" title="how to be smart">
                            <summary>Lorem ipsum dolor sit amet.</summary>
                            <sections>
                                <section id="1">
                                    <pharagraph id="1">Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, perferendis!</pharagraph>
                                </section>
                            </sections>
                        </chapter>
                    </chapters>
                </part>
            </parts>
        </book>
        <book id="1" title="How to use your brain">
            <isbn></isbn>
            <author>Muhammed Adel</author>
            <preface></preface>
            <parts>
                <part id="1" title="be smart be creative">
                    <chapters>
                        <chapter id="1" title="how to be smart">
                            <summary>Lorem ipsum dolor sit amet.</summary>
                            <sections>
                                <section id="1">
                                    <pharagraph id="1">Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, perferendis!</pharagraph>
                                </section>
                            </sections>
                        </chapter>
                    </chapters>
                </part>
            </parts>
        </book>
    </books>
</library>
