=== mhamdadel/portfolio12/projects/xml/d2/Q2/Day2.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="library">
        <xs:complexType> 
            <xs:sequence> <!--(xs:all) or (xs:choice)-->
                <xs:element name="libern" type="xs:string"/>  
                <xs:element name="book" type="Book" maxOccurs="unbounded"/>
            </xs:sequence>
            
            <xs:attribute name="location" type="xs:string"/>
            <xs:attribute name="description" type="xs:string"/>        
        </xs:complexType>
    </xs:element> 
    
    <xs:complexType name="Book"> 
        <xs:sequence> <!--(xs:all) or (xs:choice)-->
            <xs:element name="author" type="xs:string"/>  
            <xs:element name="preface" type="xs:string"/>
            <xs:element name="part" type="Part" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="isbn" type="xs:string"/>
        <xs:attribute name="book_title" type="xs:string"/>        
    </xs:complexType>
    
    <xs:complexType name="Part"> 
        <xs:sequence>
            <xs:element name="chapter" type="Chapter" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="part_title" type="xs:string"/>      
    </xs:complexType>
    
    <xs:complexType name="Chapter"> 
        <xs:sequence>
            <xs:element name="summary" type="xs:string"/>
            <xs:element name="content" type="Content" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="chap_title" type="xs:string"/>      
    </xs:complexType>
    
    <xs:complexType name="Content"> 
        <xs:sequence>
            <xs:element name="p" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>   
    </xs:complexType>
</xs:schema>

=== mhamdadel/portfolio12/projects/xml/d2/Q2/Day2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->

<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="Day2.xsd"
         location="ain_shams" description="it's a lib">
    <libern>Itians</libern>
    <book isbn="_book1" book_title="BOOK1">
        <author>momo</author>
        <preface>how to think</preface>
        <part part_title="part">
            <chapter chap_title="chap1">
                <summary>how to be opetmistc</summary>
                <content>
                    <p> hello world! </p>
                </content>
            </chapter>
        </part>
        <part part_title="part">
            <chapter chap_title="chap1">
                <summary>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste nobis aperiam rerum hic iure vel saepe accusantium fuga aspernatur, numquam ad dolor optio? Cum, ut?</summary>
                <content>
                    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident, repudiandae ex! Voluptates culpa, voluptatum aspernatur, sunt reiciendis praesentium quas architecto eligendi quae fugit minus saepe.</p>
                    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quaerat impedit commodi quas. Ut ducimus ea harum veritatis. Eius porro ipsa quibusdam enim. Saepe, optio hic.</p>
                </content>
            </chapter>
        </part>
    </book>
    <book isbn="_book2" book_title="BOOK2">
        <author>Man1</author>
        <preface>Welcome to book1</preface>
        <part part_title="part">
            <chapter chap_title="chap1">
                <summary>chap1 about iti</summary>
                <content>
                    <p>hello1</p>
                </content>
            </chapter>
        </part>
        <part part_title="part">
            <chapter chap_title="chap1">
                <summary>chap1 about iti</summary>
                <content>
                    <p>hello1</p>
                    <p>hello1</p>
                </content>
            </chapter>
        </part>
    </book>
</library>
